# Generated by Django 3.2.6 on 2022-07-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20220709_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imager',
            new_name='imagen',
        ),
    ]
