# Generated by Django 3.2.6 on 2022-07-04 13:14

import Servicios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(upload_to=Servicios.models.upload_imagen_servicios),
        ),
    ]
